[package]
name = "uigraf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
hex_color = "3.0.0"
rgb = "0.8.37"
textplots = "0.8.6"
